# Generated by Django 5.0.4 on 2024-04-30 22:25

import base.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=60, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('number_telephone', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('cit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_telephone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Preparation', 'Preparation'), ('Dispatch', 'Dispatch'), ('Done', 'Done'), ('Canceled', 'Canceled')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ImageField(upload_to='')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.city')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.region'),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('diagonal_screen', models.FloatField()),
                ('built_in_memory', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_price', models.IntegerField(null=True)),
                ('weight', models.FloatField()),
                ('number_stock', models.IntegerField()),
                ('release_date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_one_phone', models.IntegerField()),
                ('title_telephone', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.delivery')),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=base.models.get_telephone_image_upload_path)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=base.models.get_user_image_upload_path)),
                ('number_telephone', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('telephone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
