# Generated by Django 5.0.4 on 2024-05-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_order_user_id_alter_provider_second_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephoneimage',
            old_name='telephone_id',
            new_name='telephone',
        ),
    ]
