# Generated by Django 5.0.4 on 2024-05-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_address_id_userprofile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cit_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='city_id',
            new_name='city',
        ),
    ]
