# Generated by Django 5.0.4 on 2024-05-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_cit_id_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='telephone_id',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='delivery_id',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='telephone_id',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='telephone_id',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='telephone_id',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='telephone_id',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
