# Generated by Django 5.0.4 on 2024-05-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_full_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_telephone',
        ),
    ]
