# Generated by Django 5.0.4 on 2024-05-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_userprofile_address_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='order_product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('telephone_image', models.ImageField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telephone')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
