# Generated by Django 5.0.4 on 2024-05-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_region_city_remove_address_region_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Vendor',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='provider',
            new_name='vendor',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
