# Generated by Django 5.0.4 on 2024-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_first_name_order_last_name_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'PREPARATION'), ('DISPATCH', 'DISPATCH'), ('DONE', 'DONE'), ('CANCELED', 'CANCELED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order_product_details',
            name='telephone_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
