# Generated by Django 5.0.4 on 2024-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENDED', 'SENDED'), ('DONE', 'DONE'), ('CANCELED', 'CANCELED')], max_length=20),
        ),
    ]
