# Generated by Django 5.0.4 on 2024-05-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_deliverydetails_delivery_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_details',
            name='title_telephone',
        ),
    ]
