# Generated by Django 5.0.4 on 2024-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_delivery_details_title_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(),
        ),
    ]
