# Generated by Django 5.0.4 on 2024-05-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_price_delivery_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product_details',
            name='telephone_image',
        ),
    ]
