# Generated by Django 5.0.4 on 2024-05-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_order_product_details_telephone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_price',
        ),
    ]
