# Generated by Django 5.0.4 on 2024-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_userprofile_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_price',
        ),
    ]
